travis:
  secure:
    BINSTAR_TOKEN: NOMka2MHmempSfq3/dFykgB8dbnTVBLorS0MUEG4g0NwZIlheUZqfyXsnOuh7Avb/Jdbot63PAi5TAR7D9B6theskWaUxqXGRhZ3pnWiqv30bERHUaSmUJ+a3H5aU40LVUTyn4thm7/2OMoX1B+W3ZpdprxnBDRfED0uO9U/2j+MXeRBUg5aVy3yw/Ur6mYorIc2eVjY4YCp09uiZt/lFNh33KMOZL4BDI8Z4yfOJQfOzImq2b+p3UVdWMB7JO07vmVy83KRZL1RF2IQ7uquzCXDYOVZVawY1yCFF2iIJdFqeCQjFrLsEHgdbNGDvREYGpmTUNCvMFebMH8gUGpWK/qgTxMparvfKb2MuiQ39EKLgpZgWpk5ta4YFCSzlh80n243uzWmt6GOvyNMLc6y6pFBNDSF9beALqNMzfio0uN2EnJ6VmCcJhiwYCaIZvKm+R2vhlXijckchQ/V3R/VkjsPgNW+bLknJs8H4hLSblIyuwj0t28WFYmVVq+Vq+mGlbw3erUYnXC5/kUeP+eiQEDbbva1EHZ8IVGL9/pacQBJmQVMb0kSJTqtNBjYC9TumrhHWD6DwpMBIQqXjsLUL7MRuQ0khGSqvEQwpx+Et2iCNIjTijxIIQ+ETLF0R98JWwOURFz7I7Z+I37Zq6cVWIgkT3GTGDI17R7vuWsrVLY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
