travis:
  secure:
    BINSTAR_TOKEN: eozhc+i+oolJCfhEB/GyrBK4CT53pDSo7cnSTOgLCN5FkSN83y+g9EeAgDjP46LvsmK3X2eumOxOMnV+G1Kg554hVWnojWSUDGlC2QTUtrD+Cw2YGbCNY8hQ1vwgrreFnYkrq6V6FZ20TSWW3sG4hmoceeQxjrApe/4cd2IfiTcZKI3f+//q0/9ipfsE3nTZuiLBuvqX2BOPyFNbeRdzb20D4Uk7lTvBMc+9Wx5vrQP98xAGfkWHs68XtKHSsbDe7XFYtYA2TWLUfLKK7FO2y3iotsP7Gcd2h1/sBwmJ2AXMPz/9hbLZfySBm+dUMlPXyccd7X/Z+gD7dBqLq+IK7PVv5E06Hn5Y+q9almp92BK8aHyTqBO9jFKjf+P2mE5ESQYND8YGGA9jwEKCSdyowz3zDeXjKaNzoUSyZqg81gkoEqCA9kZFicE++i8RBSKrNFYtdAu1dzJEs0jKWDXgK7A4qdzJQRrCsO3jig73xoPW6yLsqQLJILsI+75ljrOadzVB2uLDu1aiWJVuzFvcyWCxcbAdIAJt/WoRVaLJTu574WhTLsTcNvlWhMVlraxOPPJR8zSkqZBgq5BqKFcuLLaEkW0oCb9o9Xsfu7/ZNbkwPo4AED8EOdhzLwI2uundyonKCMhrEvvjyaP0Ec4B3KMZ2Tkj7otswEcT63MfLic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
