travis:
  secure:
    BINSTAR_TOKEN: DCpEhptisOENBBYr55dkbYNU6skpC3fQHPj1kLSq5o/p0Wji+tarpmiE1KCoVcjYqDfs+iCYMyDO/g8zQsCQudnJ4u0QteWDlL5njrjMazxUhujjkP4OQD0L95Z7SxqOdyiovZL8XbkeCj8faI8jU7OrqzZ1McaMoGqQ2ljnfqcI2MIH0/c8y73bZ8TepmNpDiX37I94ez4J95Dci2kY9cBUX91aUhd+F5SyxMyqFojiKCiZNcgsE4MvBXuZP71ttl/9t0+dgN+tJNlp2xlFjFZD1x7aBewDHDynqiPVRWaDZDzuVGsMefB7rgkuqk43qwYgRsjjrlRml8y5KOsfDvRLQiJWqptwwvhyGDWdhqUCQDWArpxsBPAAAuJbHtDUeVh5o67CFZoRP8qsKTgCavWVunXlgDx/ACNUQQylZMr6PvQNNGXD3Gpi8agcs6GT+t7sK6rXjzIYmkkWn5VIqfkv25e99LYv0Pf57lTKtH9rSrlVmAxNw6vnuthMyKBttbflJn/JRK9nhl/JMrwbGut+Gboj2VfTtojlsODXeKxTWXLP1oDmflunLCwBxhPBAdfWtz5vyFR/ZoVH1BRmGHybkgvxVDm/IMNJATEk5Tj6Be/oSWMNs1QHDPm9M1ARqnIC6uQ+xWPG+USoFu1wZ4c9EwWwt0daMTiMxepoSro=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
