travis:
  secure:
    BINSTAR_TOKEN: GNAjGbdoC8f0USsGmgnNMeJeT2nrE6vz4pF2acvBtRqXOp4rh1/fMJXsjS/fAyUt5HylnpoPbGRlM8f+C0Di2KxaxScFPWG6PTv7QhzmNmn2zxg8doy8qt8XtXIHszLT4E0raayoUlTfkoe8rpiz9xKoZ2i6LBu608aL1BK3HbghRQSEsGjO6dL/AoTx430Ittm1qEjCs5JA2lE6UjWjwLKtPkrxVgNGpIJp9owGUhwWjhmVGvhjcnjlTm/xdnk8U88gNhwV0ACHlW420n5y2DjQjREEtW5vL1y1chtwhegF53HFz0lLhmNEMx8gQNwIiZDSc02NMb6x1OH5KYLkZPbrPX51fcsTXLmrGBvxCCqZgZ1VPzto+V1XXVBlxEdjOGnsRufvjcBUlOAYmD0ppWxsLBOWL2UthmirZrvXHCu+nTl3HaEvFA451Yw8Q5UHD2wlcNSNS7YFQJM5OdDWyCa5ZjuYF1ZLA+dobHDC8L/iefdeD13tnr6SwWNMV5H0YuZ4hUCwhy3BFP8kbhfZLUZhQkC5h1H3y3QqAUK7lItjBBSe9MOY1HlQXU/L2xGunEkym95+njQseGNwoVUEQDeWU2v4HR+Xw/7wxLpEeC5xEzB9AURZEgyXlok48t87OLijl6PkoKjOZuQOkvC3cfHnXimnAR6N5xd9Fjvjeps=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
