travis:
  secure:
    BINSTAR_TOKEN: Krpbar/KSUkUAHiGWVTrdI+KHzepd7UNz1WxOytb/j798GItIyzKqCAVppL5aJ5B1Nm/L/5IQMat8IhZzsIpj8J5p9heIfh1b8tfDbxGr4aRg/Ald3pnSZHZgdMEz5Iofi5uL3Q1raQc/b2C2yG9Ik2PA66qMcIDX4wr9MSugjG6HT1cE4JLY56DoSDXD4ujMxDJtYc4zOAQru/mMxkr+RH3XuRa6Pu8mRcwBS63bqEiZJDALvuCfoEGKQFYf1ZsDh0h2bmgXBy6t3AvvYL7jyh8ReqGGzO0qxd6uCs7Y+7HCzoY8WPC1eI+0iyBpuovtqmNDISu06TePfNDJqGxPmAGbe33iHr6tMkRTdAHqizJBvQhD3HxtKzA3sCVoqOAJR9/gMUz2NczgVzF7Lh7A0IrHpa1zG/fW9dfs5vMES+ydji8H5heaO1n+/XsNMbQyGz/8VsSRKkqnX8+EaBuGrPqfDZ6JKh+Zo6NMnne9PsHuR6vbYG2OuNGhaRfhecjdRwRiHjg4R4kBS/MT6y7u5vbllXseUJt4yx425O0JPeQc8uyGD2u4O7Ul/xPnT1Lm3MWE3XMlSYXM+kLRjjFGQxwohQMuJGGNUE1gPjZNt6tIw3wGUDnEvgKqoA+XEucexr0nbeByXcih669hSvTvHvEq2xPH1nEShaKt9naD3A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
